sesion2:	sesion2.cpp Permutation.o SimplifiedDes.o
		g++ sesion2.cpp Permutation.o SimplifiedDes.o -o sesion2
		./sesion2
Permutation.o:	Permutation.cpp	Permutation.h
		g++ -c Permutation.cpp
SimplifiedDes.o:  SimplifiedDes.cpp SimplifiedDes.h
		  g++ -c SimplifiedDes.cpp
clean:
	rm -f *.o sesion2
