permutation:	practice2.cpp Permutation.o 
		g++ practice2.cpp Permutation.o -o permutation
		./permutation
Permutation.o:	Permutation.cpp Permutation.h
		g++ -c Permutation.cpp
clean:	
		rm -f *.o permutation
